module.exports = {
    apps: [
        {
            name: "aashey-server",
            cwd: "./server",
            script: "npm",
            args: "start",
            env: {
                NODE_ENV: "production",
                PORT: 4002,
            },
            env_production: {
                NODE_ENV: "production",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "500M",
            error_file: "/root/.pm2/logs/aashey-server-error.log",
            out_file: "/root/.pm2/logs/aashey-server-out.log",
            log_date_format: "DD/MM/YYYY HH:mm:ss",
        },
        {
            name: "aashey-client",
            cwd: "./client",
            script: "node_modules/next/dist/bin/next",
            args: "start -p 3002",
            env: {
                NODE_ENV: "production",
                PORT: 3002,
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "800M",
            error_file: "/root/.pm2/logs/aashey-client-error.log",
            out_file: "/root/.pm2/logs/aashey-client-out.log",
            log_date_format: "DD/MM/YYYY HH:mm:ss",
        },
        {
            name: "aashey-front",
            cwd: "./front",
            script: "npm",
            args: "run preview -- --port 4175 --host 0.0.0.0",
            env: {
                NODE_ENV: "production",
                PORT: 4175,
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "500M",
            error_file: "/root/.pm2/logs/aashey-front-error.log",
            out_file: "/root/.pm2/logs/aashey-front-out.log",
            log_date_format: "DD/MM/YYYY HH:mm:ss",
        },
    ],
};